version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven        
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=318550974018.dkr.ecr.us-east-1.amazonaws.com/simulator
  build:
    commands:
      - echo Build started on `date`
      - echo Creating the jar file
      - mvn package spring-boot:repackage  
      - echo Building the simulator docker image          
      - docker build -t $REPOSITORY_URI:simulator -f Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:simulator
      - echo DONE...   
artifacts:
    files: 
      - imagedefinitions.json
      - target/simulator-0.0.1-SNAPSHOT.jar
